name: 'CI'

on: [push]

concurrency:
  group: healthier-backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_and_analysis:
    name: linters and code analysis
    runs-on: ubuntu-22.04

  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Yaml lint
      uses: ibiqlik/action-yamllint@v3
      with:
        config_file: .yamllint.yml
        no_warnings: true
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'poetry'
    - run: poetry install
    - name: Check code style
      run: flake8 backend/healthier/
